In [1]:
import pvlib
from pvlib import pvsystem
import pandas as pd; import numpy as np 
from IPython.display import clear_output
from datetime import datetime, timedelta

In [3]:
import urllib3, socket
from urllib3.connection import HTTPConnection

HTTPConnection.default_socket_options = ( 
     HTTPConnection.default_socket_options + [
     (socket.SOL_SOCKET, socket.SO_SNDBUF, 2000000), #1MB in byte
     (socket.SOL_SOCKET, socket.SO_RCVBUF, 2000000)
])

In [4]:
weather  = pd.read_csv("RL_Data/00_General/00_Weather/0_weather.csv")
insert_rows = 12  # how many rows to insert

In [5]:
def get_pv_data(day_weather_300,i):
     temp_air = day_weather_300.iloc[i].TDryBul
     dni = day_weather_300.iloc[i].HDirNor
     dhi = day_weather_300.iloc[i].HDifHor
     ghi = day_weather_300.iloc[i].HHorIR 
     w_sp = day_weather_300.iloc[i].winSpe
     return temp_air,dni,dhi,ghi,w_sp

In [6]:
day_no = 1

day_weather = weather.iloc[day_no*24:(day_no+1)*24]
day_weather.index = range(0, insert_rows * len(day_weather), insert_rows)
# create new_df with added rows
day_weather_300 = day_weather.reindex(index = range(insert_rows * len(day_weather)))
day_weather_300 = day_weather_300.interpolate()  

day_weather_300

,TDryBul,TDewPoi,relHum,pAtm,HHorIR,HGloHor,HDirNor,HDifHor,winDir,winSpe,nTot,nOpa,ceiHei,time
0,-3.900000,-6.1,85.000000,99000.0,0.0,0.0,0.0,0.0,170.0,2.100000,2.000000,2.000000,77777.0,86400.0
1,-3.808333,-6.1,84.416667,99000.0,0.0,0.0,0.0,0.0,172.5,2.183333,2.166667,2.083333,77777.0,86700.0
2,-3.716667,-6.1,83.833333,99000.0,0.0,0.0,0.0,0.0,175.0,2.266667,2.333333,2.166667,77777.0,87000.0
3,-3.625000,-6.1,83.250000,99000.0,0.0,0.0,0.0,0.0,177.5,2.350000,2.500000,2.250000,77777.0,87300.0
4,-3.533333,-6.1,82.666667,99000.0,0.0,0.0,0.0,0.0,180.0,2.433333,2.666667,2.333333,77777.0,87600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,0.000000,-0.6,96.000000,97800.0,0.0,0.0,0.0,0.0,320.0,2.600000,10.000000,10.000000,180.0,169200.0
284,0.000000,-0.6,96.000000,97800.0,0.0,0.0,0.0,0.0,320.0,2.600000,10.000000,10.000000,180.0,169200.0
285,0.000000,-0.6,96.000000,97800.0,0.0,0.0,0.0,0.0,320.0,2.600000,10.000000,10.000000,180.0,169200.0
286,0.000000,-0.6,96.000000,97800.0,0.0,0.0,0.0,0.0,320.0,2.600000,10.000000,10.000000,180.0,169200.0
287,0.000000,-0.6,96.000000,97800.0,0.0,0.0,0.0,0.0,320.0,2.600000,10.000000,10.000000,180.0,169200.0

In [54]:
day_weather_300[12*6:12*7]

,TDryBul,TDewPoi,relHum,pAtm,HHorIR,HGloHor,HDirNor,HDifHor,winDir,winSpe,nTot,nOpa,ceiHei,time
72,-0.6,-5.6,69.0,99000.000000,0.000000,0.000000,0.0,0.000000,200.000000,2.6,10.0,10.0,7620.000000,108000.0
73,-0.6,-5.6,69.0,98991.666667,3.583333,0.666667,0.0,0.666667,199.166667,2.6,10.0,10.0,7188.333333,108300.0
74,-0.6,-5.6,69.0,98983.333333,7.166667,1.333333,0.0,1.333333,198.333333,2.6,10.0,10.0,6756.666667,108600.0
75,-0.6,-5.6,69.0,98975.000000,10.750000,2.000000,0.0,2.000000,197.500000,2.6,10.0,10.0,6325.000000,108900.0
76,-0.6,-5.6,69.0,98966.666667,14.333333,2.666667,0.0,2.666667,196.666667,2.6,10.0,10.0,5893.333333,109200.0
77,-0.6,-5.6,69.0,98958.333333,17.916667,3.333333,0.0,3.333333,195.833333,2.6,10.0,10.0,5461.666667,109500.0
78,-0.6,-5.6,69.0,98950.000000,21.500000,4.000000,0.0,4.000000,195.000000,2.6,10.0,10.0,5030.000000,109800.0
79,-0.6,-5.6,69.0,98941.666667,25.083333,4.666667,0.0,4.666667,194.166667,2.6,10.0,10.0,4598.333333,110100.0
80,-0.6,-5.6,69.0,98933.333333,28.666667,5.333333,0.0,5.333333,193.333333,2.6,10.0,10.0,4166.666667,110400.0
81,-0.6,-5.6,69.0,98925.000000,32.250000,6.000000,0.0,6.000000,192.500000,2.6,10.0,10.0,3735.000000,110700.0
82,-0.6,-5.6,69.0,98916.666667,35.833333,6.666667,0.0,6.666667,191.666667,2.6,10.0,10.0,3303.333333,111000.0
83,-0.6,-5.6,69.0,98908.333333,39.416667,7.333333,0.0,7.333333,190.833333,2.6,10.0,10.0,2871.666667,111300.0

In [8]:
coordinates = [(42.8, -88.0, 'Chicago', 700, 'Etc/GMT+6')]     


train_days = [1,2,3,5,6,8,9,10,11,12,16,17,18,19,20,23,24,25,26,27,29,30,32,33,34,36,37,38,39,41,43,44,45,47,48]
test_days = [4,13,15,22,31,40,46]

tot_days = train_days+test_days 


for day_no in [7,14,28]:
     day_weather = weather.iloc[day_no*24:(day_no+1)*24]
     pv_df =pd.DataFrame(columns=['south_pv','east_pv','west_pv','car_port_pv'],dtype=np.float64)
     day_weather.index = range(0, insert_rows * len(day_weather), insert_rows)
     # create new_df with added rows
     day_weather_300 = day_weather.reindex(index = range(insert_rows * len(day_weather)))
     day_weather_300 = day_weather_300.interpolate()     
     for i in range(12*24):
          temp_air,dni,dhi,ghi,w_sp = get_pv_data(day_weather_300=day_weather_300,i=i)
          print ("day_no: {},i: {}".format(day_no,i))
          print ("temp air: {}; dni: {}; dhi: {}; ghi: {}; w_sp: {}".format(temp_air,dni,dhi,ghi,w_sp))
          if (i<12*5)or(i>18*12):
               south_pv = 0 
               east_pv = 0 
               west_pv = 0 
               car_port_pv = 0 
          else:
               south_pv = get_pv_output(temp_air=temp_air,
                                   dni=dni,
                                   dhi=dhi,
                                   ghi=ghi,
                                   w_sp=w_sp,
                                   no_of_modules=1,
                                   surface_tilt=46,
                                   azimuth=180,
                                   hours=i*300/3600,
                                   day_no=day_no)
               
               east_pv = get_pv_output(temp_air=temp_air,
                                   dni=dni,
                                   dhi=dhi,
                                   ghi=ghi,
                                   w_sp=w_sp,
                                   no_of_modules=1,
                                   surface_tilt=19,
                                   azimuth=90,
                                   hours=i*300/3600,
                                   day_no=day_no)

               west_pv = get_pv_output(temp_air=temp_air,
                                   dni=dni,
                                   dhi=dhi,
                                   ghi=ghi,
                                   w_sp=w_sp,
                                   no_of_modules=1,
                                   surface_tilt=19,
                                   azimuth=270,
                                   hours=i*300/3600,
                                   day_no=day_no
                                   )

               car_port_pv = get_pv_output(temp_air=temp_air,
                         dni=dni,
                         dhi=dhi,
                         ghi=ghi,
                         w_sp=w_sp,
                         no_of_modules=1,
                         surface_tilt=35,
                         azimuth=180,
                         hours=i*300/3600,
                         day_no=day_no)

          
          df1 = pd.DataFrame({'south_pv':[south_pv],'east_pv':[east_pv],'west_pv':[west_pv],'car_port_pv':[car_port_pv]})
          pv_df = pd.concat([pv_df, df1])
          print (df1)

          if i%12==0:                    
               clear_output(wait=True)


     pv_df.to_pickle("RL_Data/00_General/01_PV/"+str(day_no)+".pkl")

day_no: 28,i: 277
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 278
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 279
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 280
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 281
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 282
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 283
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 284
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 285
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 286
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0
day_no: 28,i: 287
temp air: -13.9; dni: 0.0; dhi: 0.0; ghi: 0.0; w_sp: 3.6
   south_pv  east_pv  west_pv  car_port_pv
0         0        0        0            0

In [7]:
def get_pv_output(temp_air,dni,dhi,ghi,w_sp,no_of_modules,surface_tilt,azimuth,hours,day_no):
     energies = {}
     
     # coordinates = [(42.8, -88.0, 'Chicago', 182, 'Etc/GMT+6')]  

     coordinates = [(32.2, -88.0, 'Tucson', 182, 'Etc/GMT+7')]   
     sandia_modules = pvlib.pvsystem.retrieve_sam('SandiaMod')

     # print ("Sandia modules: {}".format(sandia_modules))
     sapm_inverters = pvlib.pvsystem.retrieve_sam('cecinverter')
     module = sandia_modules['Canadian_Solar_CS5P_220M___2009_']
     inverter = sapm_inverters['ABB__MICRO_0_25_I_OUTD_US_208__208V_']
     temperature_model_parameters = pvlib.temperature.TEMPERATURE_MODEL_PARAMETERS['sapm']['open_rack_glass_glass']
     

     tmys = []
     for location in coordinates:
          latitude, longitude, name, altitude, timezone = location
          weather = pvlib.iotools.get_pvgis_tmy(latitude, longitude,
                                                  map_variables=True)[0]

          # print ("weather")
          # print (weather[0:48])



          
          weather = weather.iloc[0:1] 
          weather.index = weather.index +timedelta(hours=6)+timedelta(hours=day_no*24+hours)
          
          weather.index.name = "utc_time"
          
          tmys.append(weather)

     # print ("Weather Check")
     # print (weather)
     
     system = {'module': module, 'inverter': inverter,'surface_azimuth': azimuth}    

     weather['dni'] = dni
     weather['ghi'] = ghi
     weather['dhi'] = dhi
     weather['wind_speed'] = w_sp
     weather['temp_air'] = temp_air

     for location, weather in zip(coordinates, tmys):
          latitude, longitude, name, altitude, timezone = location
          system['surface_tilt'] = surface_tilt
          solpos = pvlib.solarposition.get_solarposition(
               time=weather.index,
               latitude=latitude,
               longitude=longitude,
               altitude=altitude, 
               temperature=weather["temp_air"],
               pressure=pvlib.atmosphere.alt2pres(altitude),
          )
          dni_extra = pvlib.irradiance.get_extra_radiation(weather.index)
          airmass = pvlib.atmosphere.get_relative_airmass(solpos['apparent_zenith'])
          pressure = pvlib.atmosphere.alt2pres(altitude)
          am_abs = pvlib.atmosphere.get_absolute_airmass(airmass, pressure)
          aoi = pvlib.irradiance.aoi(
               system['surface_tilt'],
               system['surface_azimuth'],
               solpos["apparent_zenith"],
               solpos["azimuth"],
          )
          total_irradiance = pvlib.irradiance.get_total_irradiance(
               system['surface_tilt'],
               system['surface_azimuth'],
               solpos['apparent_zenith'],
               solpos['azimuth'],
               weather['dni'],
               weather['ghi'],
               weather['dhi'],
               dni_extra=dni_extra,
               model='haydavies',
          )
          cell_temperature = pvlib.temperature.sapm_cell(
               total_irradiance['poa_global'],
               weather["temp_air"],
               weather["wind_speed"],
               **temperature_model_parameters,
          )
          effective_irradiance = pvlib.pvsystem.sapm_effective_irradiance(
               total_irradiance['poa_direct'],
               total_irradiance['poa_diffuse'],
               am_abs,
               aoi,
               module,
          )
          dc = pvlib.pvsystem.sapm(effective_irradiance, cell_temperature, module)
          ac = pvlib.inverter.sandia(dc['v_mp'], dc['p_mp'], inverter)

          if ac[0]<0:
               ac[0]=0

          return ac[0]*no_of_modules

In [136]:
temp_air = 3
dni = 230
dhi = 400
ghi = 100
w_sp = 3 
hours= 17

get_pv_output(temp_air=temp_air,
                              dni=dni,
                              dhi=dhi,
                              ghi=ghi,
                              w_sp=w_sp,
                              no_of_modules=1,
                              surface_tilt=46,
                              azimuth=180,
                              hours=hours,
                              day_no=day_no)

weather

0.0

In [154]:
day_no=1

pv_df=pd.read_pickle("RL_Data/00_General/01_PV/"+str(day_no)+".pkl")

pv_df.reset_index(drop=True,inplace=True)

pv_df

     south_pv  east_pv  west_pv  car_port_pv
0         0.0      0.0      0.0          0.0
1         0.0      0.0      0.0          0.0
2         0.0      0.0      0.0          0.0
3         0.0      0.0      0.0          0.0
4         0.0      0.0      0.0          0.0
..        ...      ...      ...          ...
283       0.0      0.0      0.0          0.0
284       0.0      0.0      0.0          0.0
285       0.0      0.0      0.0          0.0
286       0.0      0.0      0.0          0.0
287       0.0      0.0      0.0          0.0

[288 rows x 4 columns]